name: Build and publish a docker image

on:
  push:
    tags: [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          docker login ghcr.io --username hellodhlyn --password ${{ secrets.GITHUB_TOKEN }}

          docker build -t ghcr.io/hellodhlyn/pprv-rumors:latest .
          docker tag ghcr.io/hellodhlyn/pprv-rumors:latest ghcr.io/hellodhlyn/pprv-rumors:${GITHUB_REF##*/}

          docker push ghcr.io/hellodhlyn/pprv-rumors:latest
          docker push ghcr.io/hellodhlyn/pprv-rumors:${GITHUB_REF##*/}
